### ISSUE TITLE
button 

### ISSUE THREAD

**Issue by Kvazoo** [edu-prog/eduprog-ui-framework#52]
![image](https://user-images.githubusercontent.com/73490644/174487223-976f67be-422f-4878-8971-b81888bf2dd2.png)
при включении закругления, кнопка принимает странную форму

**Comment by Kvazoo** [comment]
В пункте "view" и "size" присутствует "undefined", который всё портит

**Comment by sviridovcomp** [comment]
Many thanks for your bug-report. This was solved in 460d82405fd8075f54ed176253b6788cfaeb52f0
