### ISSUE TITLE
Island

### ISSUE THREAD

**Issue by Kvazoo** [edu-prog/eduprog-ui-framework#60]
Кнопка "Show" ничего не делает.(я хз что должна показать)

**Comment by sviridovcomp** [comment]
This button doesn't have to do anything, it's just an example of the layout of ui-framework elements. 

But I agree that the name for the button is unfortunate, we'll change it in the next release.

**Comment by sviridovcomp** [comment]
This was fixed. Many thanks for your feature request

<p align="center">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/50530767/185970320-0b3cce47-1dda-43cd-bd13-a6e0567449fd.png">
</p>
