### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by Kvazoo** [edu-prog/eduprog-ui-framework#61]
"Fail" не выводит значок
![image](https://user-images.githubusercontent.com/73490644/175063694-5ed98084-50dc-463c-b088-175ae6d09cd5.png)
на светлой теме тёмное уведомление

**Comment by sviridovcomp** [comment]
Many thanks for your bug-report.

In the future, we will redesign the interaction with Notifications

**Comment by sviridovcomp** [comment]
Many thanks for you bug report, fixed in 80462709c1116f865b69fb0d0956590420681dd1
