### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Kvazoo** [edu-prog/eduprog-ui-framework#62]
![image](https://user-images.githubusercontent.com/73490644/175065257-40117f7f-4cc7-47aa-856e-6056013ca608.png)
![image](https://user-images.githubusercontent.com/73490644/175065325-c741a2ae-1ddc-49bb-950d-7e55e4e68a7f.png)
Текст на светлой теме остаётся белым

**Comment by sviridovcomp** [comment]
Many thanks for you bug report, fixed in 80462709c1116f865b69fb0d0956590420681dd1
