### ISSUE TITLE
label

### ISSUE THREAD

**Issue by Kvazoo** [edu-prog/eduprog-ui-framework#65]
![image](https://user-images.githubusercontent.com/73490644/175349663-37238982-7f65-4e97-a274-f0844ecab9da.png)
на тёмной теме текст остаётся чёрным.
при переключении "position" в "right"  происходит баг
![image](https://user-images.githubusercontent.com/73490644/175350335-ca31d6a9-3154-40e9-a833-538ea6f8c715.png)

**Comment by sviridovcomp** [comment]
Many thanks for you bug report, fixed in 80462709c1116f865b69fb0d0956590420681dd1
